### ISSUE TITLE
"Get the free book" message is out of date

### ISSUE THREAD

**Issue by jack-jjm** [javaparser/javaparser.github.io#14]
The website states that the JavaParser book is free, but it seems this is no longer the case. Could the website be updated to reflect this? It's very confusing.

**Comment by seeseemelk** [comment]
This tripped me up too. I was really confused why they claimed it was free, and also wondering why a free open-source library would put their documentation behind a pay wall.

Turns out that LeanPub decided that authors of free books should still get payed by making their books not-free (https://leanpub.com/imagine_a_world), but authors can opt out of it.

Perhaps JavaParser could opt-out of this scheme for their manual?

**Comment by matozoid** [comment]
Oh, we need @SmiddyPence for that.

**Comment by SmiddyPence** [comment]
Apologies, as mentioned LeanPub changed their model and it required an opt-out that wasn't noticed.

Should be optional to pay again now.
